config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, 
             controllers: { omniauth_callbacks: 'oauth_callbacks', confirmations: 'confirmations'  }, 
             path: :qna, path_names: { sign_in: :login, sign_out: :logout }
              
  root to: 'questions#index'

  concern :votable do
    member do
      post :vote_up
      post :vote_down
      delete :unvote
    end
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end

      resources :questions, only: [:index, :create, :show, :update, :destroy] do 
        resources :answers, shallow: true, only: [:index, :create, :show, :update, :destroy]
      end
    end
  end

  resources :questions, concerns: :votable do 
    resources :subscriptions, only: [:create, :destroy], shallow: true
    resources :comments, only: :create
    resources :answers, concerns: :votable, shallow: true, only: [:create, :update, :destroy] do
      resources :comments, only: :create
      member do 
        post :mark_as_best
      end
    end
  end
  
  get  :search, to: 'search#index'
  
  resources :attachments, only: :destroy
  resources :links, only: :destroy
  resources :rewards, only: :index

  mount ActionCable.server => '/cable'
end

app/models/question.rb
class Question < ApplicationRecord
  include Votable

  belongs_to :user
  has_many :answers, dependent: :destroy
  has_many :links, dependent: :destroy, as: :linkable
  has_many :comments, dependent: :destroy, as: :commentable
  has_many :subscriptions, dependent: :destroy

  has_many_attached :files

  has_one :reward, dependent: :destroy

  accepts_nested_attributes_for :links, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :reward, reject_if: :all_blank, allow_destroy: true

  validates :title, :body, presence: true

  after_create :calculate_reputation
  after_create :create_subscription

  private

  def calculate_reputation
    ReputationJob.perform_later(self)
  end

  def create_subscription
    subscriptions.create(user: user)
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController
  authorize_resource
  
  def index
    @questions = Question.all
    render json: @questions
  end

  def create
    @question = current_resource_owner.questions.new(question_params)

    if @question.save
      render json: @question, status: :created
    else
      render json: { errors: @question.errors }, status: :unprocessable_entity
    end
  end

  def show
    render json: question, serializer: QuestionSerializer
  end

  def update
    if question.update(question_params)
      render json: question
    else
      render json: { errors: question.errors }, status: :unprocessable_entity
    end
  end

  def destroy
    question.destroy
    render json: { messages: ['Question deleted'] }
  end

  private

  def question
    @question = Question.with_attached_files.find(params[:id])
  end

  helper_method :question

  def question_params
    params.require(:question).permit(:title, :body)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  include Voted

  before_action :authenticate_user!, except: %i[index show]
  before_action :load_question, only: %i[show edit update destroy]
  after_action :publish_question, only: [:create]

  authorize_resource

  def index
    @questions = Question.all
  end

  def show
    @answer =  @question.answers.new
    @answer.links.new
    gon.push({
               current_user_id: current_user&.id,
               question_id: @question.id
             })
  end

  def new
    @question = Question.new
    @question.links.new # .build создать алиас new
    @question.build_reward
  end

  def edit; end

  def create
    @question = current_user.questions.new(question_params)

    if @question.save
      redirect_to @question, notice: 'Your question successfully created.'
    else
      render :new
    end
  end

  def update
    @question.update(question_params)
  end

  def destroy
    if current_user&.author?(@question)
      @question.destroy
      redirect_to questions_path, notice: 'Question deleted'
    else
      redirect_to questions_path
    end
  end

  private

  def publish_question
    return if @question.errors.any?

    ActionCable.server.broadcast(
      'questions', {
        partial: ApplicationController.render(
          partial: 'questions/question',
          locals: { question: @question, current_user: current_user }
        )
      }
    )
  end

  def load_question
    @question = Question.with_attached_files.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body, files: [], links_attributes: %i[name url],
                                                    reward_attributes: %i[title image])
  end

  def subscription
    @subscription ||= question.subscriptions.find_by(user: current_user)
  end

  helper_method :subscription
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.slim
= render 'shared/errors', resource: @question

= form_with model: @question, local: true do |f|
  p
    = f.label :title
    = f.text_field :title
  p
    = f.label :body
    = f.text_field :body
  p
    = f.label :files
    = f.file_field :files, multiple: true, direct_upload: true
  
  p Links:
  p
    = render 'links/form', f: f
  p
    = render 'rewards/form', f: f

  p = f.submit 'Ask'

app/views/questions/_question.html.slim
h4= link_to question.title, question_path(question)
p= question.body

app/views/questions/_question_block.html.slim
.question data-question-id="#{@question.id}"
  h1= @question.title
  p=  @question.body
  
  = render 'votes/vote', resource: @question

  - if @question.files.attached?
    - @question.files.each do |file|
      .question_file data-file-id="#{file.id}"
        p = link_to file.filename.to_s, url_for(file)
        - if can?(:destroy, @question)
          p = link_to "Delete file", attachment_path(file), method: :delete, remote:true

  - if @question.links.present?
    .links
      p Links:
      ul
        - @question.links.each do |link|
          = render link

  h3 Comments on the question:
  .question-comment data-comment-question=@question.id
    = render @question.comments
  - if current_user.present?
    .comments-form 
      = render 'comments/form', resource: @question

  
  .question-errors
  -if can?(:update, @question)
    = link_to "Edit question", '#', class: 'edit-question-link', data: { question_id: @question.id }
  br
  -if can?(:destroy, @question)
    = link_to "Delete question", question_path(@question),
                                         method: :delete,
                                         data: { confirm: 'Are you sure?' }
  
  = form_with model: @question, local: false,  class: 'hidden', html: { id: "edit-question-#{@question.id}" } do |f|
    p
      = f.label :title, "Title question"
      = f.text_area :title
    p
      = f.label :body, "Body question"
      = f.text_area :body
    p
      = f.label :files
      = f.file_field :files, multiple: true, direct_upload: true
    p
      = render 'links/form', f: f
    p = f.submit 'Save question'

app/views/questions/index.html.slim
-if can?(:create, Question)
  p= link_to 'Ask question', new_question_path

.questions-list
  - @questions.each do |q|
    h4= link_to q.title, question_path(q)
    p= q.body

app/views/questions/new.html.slim
= render 'form'

app/views/questions/show.html.slim
.questions
  = render 'question_block', resource: @question
  .subscription
    - if can?(:create, Subscription)
      = render 'subscriptions/subscription', resource: @question

-if can?(:create, Answer)
  = render 'answers/form'

.answers
  = render @question.answers

  

  

app/views/questions/update.js.erb
$('.question-errors').html('<%= render 'shared/errors', resource: @question %>');

<% if !@question.errors.present? %>
  $('.question[data-question-id="<%= @question.id %>"]').replaceWith('<%= j render 'question_block' %>');
<% end %>