config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, 
             controllers: { omniauth_callbacks: 'oauth_callbacks', confirmations: 'confirmations'  }, 
             path: :qna, path_names: { sign_in: :login, sign_out: :logout }
              
  root to: 'questions#index'

  concern :votable do
    member do
      post :vote_up
      post :vote_down
      delete :unvote
    end
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end

      resources :questions, only: [:index, :create, :show, :update, :destroy] do 
        resources :answers, shallow: true, only: [:index, :create, :show, :update, :destroy]
      end
    end
  end

  resources :questions, concerns: :votable do 
    resources :subscriptions, only: [:create, :destroy], shallow: true
    resources :comments, only: :create
    resources :answers, concerns: :votable, shallow: true, only: [:create, :update, :destroy] do
      resources :comments, only: :create
      member do 
        post :mark_as_best
      end
    end
  end
  
  get  :search, to: 'search#index'
  
  resources :attachments, only: :destroy
  resources :links, only: :destroy
  resources :rewards, only: :index

  mount ActionCable.server => '/cable'
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    @result = SearchService.search_by(params[:body], params[:type])
  end
end

app/views/search/_form.html.slim
.search
  = form_tag search_path, method: :get do
    = select_tag :type,
            options_for_select(SearchService::TYPES, params[:type]),
            include_blank: 'Global search'
    = text_field_tag :body, params[:body]
    = submit_tag 'Search'

app/views/search/index.html.slim
.row.justify-content-center.mt-3
  - if @result.empty?
    h3 No Result
  - else
    .list-group
      - @result.each do |object|
        .list-group-item
          - if object.is_a?(Answer)
            p = link_to object.question.body, question_path(object.question)
            p = "#{object.class}: #{object.body}"
          - elsif object.is_a?(Comment)
            p = object.commentable.body
            p = "#{object.commentable.class} comment: #{object.body}"
            p = "#{object.class}: #{object.body}"
          - elsif object.is_a?(User)
            p = link_to object.email, root_path
          - else
            p = link_to object.title, question_path(object)