config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, 
             controllers: { omniauth_callbacks: 'oauth_callbacks', confirmations: 'confirmations'  }, 
             path: :qna, path_names: { sign_in: :login, sign_out: :logout }
              
  root to: 'questions#index'

  concern :votable do
    member do
      post :vote_up
      post :vote_down
      delete :unvote
    end
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end

      resources :questions, only: [:index, :create, :show, :update, :destroy] do 
        resources :answers, shallow: true, only: [:index, :create, :show, :update, :destroy]
      end
    end
  end

  resources :questions, concerns: :votable do 
    resources :subscriptions, only: [:create, :destroy], shallow: true
    resources :comments, only: :create
    resources :answers, concerns: :votable, shallow: true, only: [:create, :update, :destroy] do
      resources :comments, only: :create
      member do 
        post :mark_as_best
      end
    end
  end
  
  get  :search, to: 'search#index'
  
  resources :attachments, only: :destroy
  resources :links, only: :destroy
  resources :rewards, only: :index

  mount ActionCable.server => '/cable'
end

app/models/answer.rb
class Answer < ApplicationRecord
  include Votable

  belongs_to :question
  belongs_to :user
  has_many :links, dependent: :destroy, as: :linkable
  has_many :comments, dependent: :destroy, as: :commentable

  has_many_attached :files

  accepts_nested_attributes_for :links, reject_if: :all_blank, allow_destroy: true

  scope :sort_by_best, -> { order(best: :desc) }

  validates :body, presence: true

  after_create :email_notification

  def mark_as_best
    transaction do
      self.class.where(question_id: question_id).update_all(best: false)
      update(best: true)
      question.reward&.update!(user: user)
    end
  end

  private

  def email_notification
    NotificationJob.perform_later(self)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!, only: %i[create destroy]
  before_action :find_question, only: [:create]
  before_action :answer, only: %i[update mark_as_best destroy]
  after_action :publish_answer, only: %i[create]

  include Voted

  authorize_resource

  def create
    @answer = @question.answers.new(answer_params)
    @answer.user = current_user
    @answer.save
  end

  def update
    @answer.update(answer_params)
    @question = @answer.question
  end

  def mark_as_best
    @question = @answer.question
    @answer.mark_as_best
  end

  def destroy
    @answer.destroy if current_user&.author?(@answer)
  end

  private

  def publish_answer
    return if @answer.errors.any?

    ActionCable.server.broadcast(
      "questions/#{params[:question_id]}/answers",
      {
        partial: ApplicationController.render(
          partial: 'answers/other_answer', locals: { answer: @answer }
        ),
        current_user_id: current_user.id,
        answer: @answer
      }
    )
  end

  def find_question
    @question = Question.find(params[:question_id])
  end

  def answer
    @answer = Answer.with_attached_files.find(params[:id])
  end

  helper_method :resource

  def answer_params
    params.require(:answer).permit(:body, files: [], links_attributes: %i[name url])
  end
end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController
  authorize_resource

  def index
    @answers = question.answers
    render json: @answers
  end

  def create
    @answer = question.answers.new(answers_params)
    @answer.user = current_resource_owner

    if @answer.save
      render json: @answer, status: :created
    else
      render json: { errors: @answer.errors }, status: :unprocessable_entity
    end
  end

  def show
    answer = Answer.find(params[:id])
    render json: answer
  end

  def update
    if answer.update(answers_params)
      render json: answer, status: :created
    else
      render json: { errors: answer.errors }, status: :unprocessable_entity
    end
  end

  def destroy
    answer.destroy
    render json: { messages: ['Answer deleted.'] }
  end

  private

  def question
    @question = Question.find(params[:question_id])
  end

  helper_method :question

  def answer
    @answer = Answer.find(params[:id])
  end

  helper_method :answer

  def answers_params
    params.require(:answer).permit(:body)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.slim
- if answer.persisted?

  = render 'votes/vote', resource: answer

  .answer data-answer-form-id="#{answer.id}"
    p= answer.body
    - if answer.files.attached?
      - answer.files.each do |file|
        .file data-file-id="#{file.id}"
          p = link_to file.filename.to_s, url_for(file)
          - if can?(:destroy, answer)
            p = link_to "Delete file", attachment_path(file), method: :delete, remote:true

    - if answer.links.present?
      .links
        p Links:
        ul
          - answer.links.each do |link|
            = render link

    h3 Comments on the answer:
    .answer-comment data-comment-answer=answer.id
      = render answer.comments
    - if current_user.present?
      .comments-form 
        = render 'comments/form', resource: answer


    -if can?(:update, answer)  
      = link_to "Edit answer", '#', class: 'edit-answer-link', data: { answer_id: answer.id }
    
    -if can?(:update, answer)
      = link_to "Delete answer", answer,
                          method: :delete,
                          data: { confirm: 'Are you sure?' },
                          remote: true
    -if answer.best
      p 'It is the best answer'
    - else
      -if can?(:mark_as_best, answer)
        = link_to "Mark as best", mark_as_best_answer_path(answer),  method: :post, remote: true


    = form_with model: answer, local: false, class: 'hidden', html: { id: "edit-answer-#{answer.id}" } do |f|
      .update-errors data-form-id="#{answer.id}"
        p
          = f.label :body, "Your answer"
          = f.text_area :body
        p
          = f.label :files
          = f.file_field :files, multiple: true, direct_upload: true
        p
          = render 'links/form', f: f
        p  = f.submit 'Save'
  

app/views/answers/_form.html.slim
.answer-errors
  = render 'shared/errors', resource: @answer
  
= form_with model: [@question, @answer], local: false, class: 'new-answer' do |f|
  p
    = f.label :body
    = f.text_area :body
  p
    = f.label :files
    = f.file_field :files, multiple: true, direct_upload: true

  p Links:
  p
    = render 'links/form', f: f
        
  p = f.submit 'Answer'

app/views/answers/_other_answer.html.slim
p= answer.body
.vote-score data-vote-id='#{answer.class.name.underscore}-#{answer.id}'
  p = answer.rating

app/views/answers/create.js.erb
$(".answer-errors").html('<%= render 'shared/errors', resource: @answer %>');

<% if @answer.persisted? %>
  $('.answers').append('<%= j render @answer %>');
  $('.new-answer #answer_body').val('');
<% end %>

app/views/answers/destroy.js.erb
$('.answer[data-answer-form-id="<%= @answer.id %>"]').remove();

app/views/answers/mark_as_best.js.erb
$('.answers').html('<%= j  render @question.answers.sort_by_best %>');

app/views/answers/update.js.erb
$('.update-errors[data-form-id="<%= @answer.id %>"]').html('<%= render 'shared/errors', resource: @answer %>');

<% if !@answer.errors.present? %>
  $('.answer[data-answer-form-id="<%= @answer.id %>"]').html('<%= j render @answer %>');
<% end %>